### ISSUE TITLE
Code refactoring: redis_snapshot_name module should be outside api-gateway

### ISSUE THREAD

**Issue by kamoljan** [microservices-today/IaC-platform#82]
`redis_snapshot_name` should be outside [api-gateway](https://github.com/microservices-today/IaC-platform/blob/master/modules/api-gateway/api-gateway.dummy#L8)

**Comment by neethugeorge** [comment]
@kamoljan We have moved `redis_snapshot_name` out of [api-gateway](https://github.com/microservices-today/IaC-platform/blob/master/modules/api-gateway/api-gateway.dummy). Currently, it is placed in [elasticache](https://github.com/microservices-today/IaC-platform/blob/master/modules/elasticache/elasticache.dummy).

**Comment by kamoljan** [comment]
@neethugeorge thank you!
